version: "3.8"

services:
  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8000:8000"
    networks:
      - auth-network

  auth-service:
    build: ./backend/auth-service
    ports:
      - "8001:8001"
    networks:
      - auth-network
    environment:
      - NODE_ENV=production

  mfa-service:
    build: ./backend/mfa-service
    ports:
      - "8002:8002"
    networks:
      - auth-network
    environment:
      - NODE_ENV=production

  session-service:
    build: ./backend/session-service
    ports:
      - "8003:8003"
    networks:
      - auth-network
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - auth-network
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
      - frontend
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
